### ISSUE TITLE
It's not running

### ISSUE THREAD

**Issue by tvhsin** [NouNouDz/Discord-Bot-Template#6]
I've cloned it on replit but it doesn't run.

**Comment by BlueTree242** [comment]
Normal lmao

**Comment by NouNouDz** [comment]
Try to put the files that are in `src` folder to the main folder

**Comment by BlueTree242** [comment]
Dude no how can it run without a server like express

**Comment by BlueTree242** [comment]
This is the reason

**Comment by NouNouDz** [comment]
You can run it without a server because its a landing page.

**Comment by BlueTree242** [comment]
Me thinking.... Does replit support that? Maybe lol
